add nid login fork
OpenEduTW/edx-platform pull request #3
Opened 2019-04-12 17:24 UTC by guangyaw

Guangyaw add nid login fork

2019-04-16 14:35 UTC, yrchen requested changes
幾點意見供參考：

1. 如果直接修改現有 student 的 model, 之後版本變更時的 migration 編號衝突要怎麼解決？有考慮過新增一個不同的 apps 而非修改現有的 apps 嗎？
2. 要 import 新的 package 的話，請參考 Django 的開發慣例，先依照英文順序 import 外部 package, 再來 import Django 相關 package，目前的順序看來沒有任何根據
3. 註解的使用僅需於程式的初始處增加即可，結束時不需要再增加結尾的註解
4. 建議 "NID" 這樣的名字改為 "FCU NID"，"校園ID" 改成 "逢甲校園 ID"，除非今天這個 NID 的支援是通用的，不然現在我認知上是僅有逢甲在使用，系統需要做出清楚的標示
5. 有任何系統畫面可以參考嗎？

2019-04-16 14:45 UTC, yrchen commented on common/djangoapps/student/views/login.py
> +    return redirect('https://opendata.fcu.edu.tw/fcuOauth/Auth.aspx?client_id=636833515976.43713f960b014ec185a62ac110c4c6dc.www.openedu.tw&client_url=https://courses.openedu.tw'+returnto)
這種直接寫在 code 裡面的路徑跟 ID 建議避免，如果是獨立的 apps, 可以另外設計一個 model (e.g., class FCUNIDConfiguration 用來紀錄參數，保留程式的彈性

2019-04-16 14:45 UTC, yrchen commented on common/djangoapps/student/views/login.py
> +    # data = {
這種沒有需要保留的註解建議刪除

2019-04-16 14:45 UTC, yrchen commented on lms/urls.py
> +
建議考慮新增獨立的 apps, 相關 urls 設定另外 include 進來，減少對原本專案中的核心檔案大幅修改，徒增後續與 upstream merge 的困擾

2019-04-16 15:45 UTC, guangyaw commented
> 幾點意見供參考：
> 
> 1. 如果直接修改現有 student 的 model, 之後版本變更時的 migration 編號衝突要怎麼解決？有考慮過新增一個不同的 apps 而非修改現有的 apps 嗎？
> 2. 要 import 新的 package 的話，請參考 Django 的開發慣例，先依照英文順序 import 外部 package, 再來 import Django 相關 package，目前的順序看來沒有任何根據
> 3. 註解的使用僅需於程式的初始處增加即可，結束時不需要再增加結尾的註解
> 4. 建議 "NID" 這樣的名字改為 "FCU NID"，"校園ID" 改成 "逢甲校園 ID"，除非今天這個 NID 的支援是通用的，不然現在我認知上是僅有逢甲在使用，系統需要做出清楚的標示
> 5. 有任何系統畫面可以參考嗎？

1.我不大清楚版本變更時候的做法,理解是若有升級可先以升級的版本為主,甚至先註解掉NID相關的code以更新為優先,   至於獨立app的作法目前或許還無法做到
2.這個慣例我不是很明白,你有相關資料嗎?
3.上下用註解包住對我而言將來比較清楚改了哪一些與改到哪裡,
4.使用校園ID是因為將來或許不只逢甲一家,期望是能夠整其他學校的校園ID進來,至於NID名字可照著建議改為FCU_NID
5.http://xhome.twshop.asia/login   測試站台可使用

2019-04-17 01:18 UTC, yrchen commented
> > 幾點意見供參考：
> > 
> > 1. 如果直接修改現有 student 的 model, 之後版本變更時的 migration 編號衝突要怎麼解決？有考慮過新增一個不同的 apps 而非修改現有的 apps 嗎？
> > 2. 要 import 新的 package 的話，請參考 Django 的開發慣例，先依照英文順序 import 外部 package, 再來 import Django 相關 package，目前的順序看來沒有任何根據
> > 3. 註解的使用僅需於程式的初始處增加即可，結束時不需要再增加結尾的註解
> > 4. 建議 "NID" 這樣的名字改為 "FCU NID"，"校園ID" 改成 "逢甲校園 ID"，除非今天這個 NID 的支援是通用的，不然現在我認知上是僅有逢甲在使用，系統需要做出清楚的標示
> > 5. 有任何系統畫面可以參考嗎？
> 
> 1.我不大清楚版本變更時候的做法,理解是若有升級可先以升級的版本為主,甚至先註解掉NID相關的code以更新為優先, 至於獨立app的作法目前或許還無法做到

你目前的變更會產生新的 migrations，以目前的狀況來說，最新的 migrations 是 0016_coursenrollment_course_on_delete_do_nothing.py，所以你的變更會產生 0017_xxxxx.py

但是若是今天 upstream 也作了 model 的變更時，0017 就發生衝突了

這邊的獨立 apps 指的是放在這個 projects 下 djangoapps 底下的獨立 apps, 不是一個外部獨立的 package，這有什麼理由不能做嗎？

> 2.這個慣例我不是很明白,你有相關資料嗎?

https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#imports
這邊有詳細的說明

> 3.上下用註解包住對我而言將來比較清楚改了哪一些與改到哪裡,

你還有空白可以使用，在前述網址裡面也有範例可供於參考

> 4.使用校園ID是因為將來或許不只逢甲一家,期望是能夠整其他學校的校園ID進來,至於NID名字可照著建議改為FCU_NID

如果是這樣的話，那應該試著抽象化現在的 code, 目前幾乎看起來都是客製化給 FCU 使用的內容

> 5.http://xhome.twshop.asia/login 測試站台可使用

目前我一點下 Sign in with NID 就死掉了 :(

2019-04-17 07:10 UTC, guangyaw commented
根據你的建議,
做了部份的修改

2019-04-19 09:35 UTC, guangyaw commented
請問目前這功能進度是?（pending? on going? or ?）

2019-04-19 10:30 UTC, yrchen commented
> 請問目前這功能進度是?（pending? on going? or ?）

直接修改 student model 導致未來 migrations 會與 upstream 衝突的問題沒解決，我不會 approve 目前的做法，建議你還是想想我之前留下的意見，你的答案是什麼

**這邊的獨立 apps 指的是放在這個 project 下 djangoapps 底下的獨立 app, 不是一個外部獨立的 package，這有什麼理由不能做嗎？**

2019-04-19 15:19 UTC, guangyaw commented
NID登入功能本身就不是Edx所支援的登入方法之一,
若要與系統原綁定功能一致,
勢必會更動原有APP,
從目前設計來看這功能本身就是基於系統相關的Code修改而來,
而新建App的意義在於它的功能能獨立於原有系統設計,才有額外拉出來的意義,
所以你是希望打掉目前的架構重新設計一個新App?

2019-04-19 23:49 UTC, yrchen commented
> NID登入功能本身就不是Edx所支援的登入方法之一,
> 若要與系統原綁定功能一致,
> 勢必會更動原有APP,
> 從目前設計來看這功能本身就是基於系統相關的Code修改而來,
> 而新建App的意義在於它的功能能獨立於原有系統設計,才有額外拉出來的意義,
> 所以你是希望打掉目前的架構重新設計一個新App?

我的本意一直都是：如果你直接修改 common/djangoapps/student 這個 app 的內容，以後我們要怎麼跟 upstream 做 merge? 尤其是你還改了 models, 未來 migrations 要怎麼處理？

common/djangoapps 底下另外建立新的 app 是我的提議，如果你覺得不能做，你可否告訴我上面的問題你要怎麼解決？

2019-04-19 23:52 UTC, guangyaw commented
https://hexiangyu.me/2016/06/20/django-migrations-and-how-to-manage-conflicts/
方法一  merge不能做?

2019-04-20 00:35 UTC, yrchen commented
> https://hexiangyu.me/2016/06/20/django-migrations-and-how-to-manage-conflicts/
> 方法一 merge不能做?
> 如果你認為該變數複雜度不夠高,有造成欄位名稱重複的可能性,
> 這可以更改,需要嗎?

你只考慮了 "當下" 的問題，我要考慮的是我要持續追上 upstream 的問題。

現在 hawthorn.master 下 student 的 migration 是 0016, 如果接受你的修改，我會產生出 0017
目前 ironwood.master 是 0019，請問我在升級至 ironwood 時，我要做怎樣的修改才能 merge?

如果你的答案是要我 merge ironwood.master 帶進來的 0017-0019，然後產生出 0020_merge，恭喜你，現在 master tree 已經是 0020 了，這件事情將永遠沒完沒了，我每次都要處理 migration conflict 的問題。

上述的情境才是我想請你思考獨立 app 的原因，因為在自己的 app 下，透過獨立的 model 以及 OneToOneField 去連接 model User，你依然可以確保資訊的一對一性，而非在 model UserProfile 底下增加一個其實跟 UserProfile 沒有這麼有絕對關聯的資訊，造成整個 student 下 model migrations 的一連串異動。

2019-04-30 16:19 UTC, guangyaw commented
已改為app模式  ,  請查收

2019-05-01 09:08 UTC, yrchen commented
> 已改為app模式 , 請查收

OK, 目前此 PR 有三個 commit，但是最新版本的修改會造成前面兩個 commits 的內容多數是無意義的，請試著做 squash commits 合併成一筆最新的內容，同時復原已經沒有需要修改的檔案 (e.g., student 下的 models.py)，確保僅修改到有受到影響的部分，這樣這個 commit 會比較容易 merge

btw, 因為近期就要開始嘗試升級到 ironwood, 或許修改完成以後可以試著用 ironwood.master 測試，我們一次到位升級

2019-05-01 13:03 UTC, guangyaw commented
第一個是最原始的那份 ,第二個移除註解與import排列方式  ,  第三份是將db移至app中  ,  所以應該是沒必要rebase,    你那邊不能直接用最後一個merge嗎?

2019-05-01 13:14 UTC, yrchen commented
> 第一個是最原始的那份 ,第二個移除註解與import排列方式 , 第三份是將db移至app中 , 所以應該是沒必要rebase, 你那邊不能直接用最後一個merge嗎?

PR 是 branch 對 branch 的 merge 行為，因為你的第三個 commit 與前兩個 commit 有相依關係，所以要我直接套用最後一個 commit merge 這件事情實際上還是要套用前兩個 commit，所以我才請你送 squash commits

common/djangoapps/student/models.py 這個檔案於第一個 commit 新增內容，於第三個 commit 移除內容 (同時留下一個無意義的換行)，沒有理由不做 rebase 以減少 conflict 的風險

不需要留下的紀錄請做完 rebase 再送進來，謝謝

2019-05-01 15:29 UTC, guangyaw commented
已合併,請查收

2019-05-02 03:49 UTC, yrchen commented on common/djangoapps/student/models.py
> +
這個空白有需要嗎？

2019-05-02 03:49 UTC, yrchen commented on lms/urls.py
> +
根據目前程式的邏輯，實質上觸發 nid 相關 login 的 views 還是放在 common/djangoapps/student/views/login.py，都已經有獨立的 apps 了，還是不能抽離嗎？如果是有 dependency 的需求，應該可以 import 原始的 module 進來使用？

2019-05-02 03:49 UTC, yrchen commented on lms/djangoapps/school_id_login/models.py
> +# from student.models import UserProfile
沒有需要的內容建議不要透過註解保留

2019-05-02 15:34 UTC, guangyaw commented
nid相關網址以綁定nid client   
除非重新申請一個不然無法移動該功能

2019-05-02 16:32 UTC, yrchen commented
> nid相關網址綁定nid client
> 除非重新申請一個不然無法移動該功能

誤解大了
```
from student import views as student_views
url(r'^nidreturn$', student_views.return_nid, name='nretrun_nid'),
url(r'^unlink_account$', student_views.unidlink, name='unidlink_account'),
```
跟
```
from school_id_login import views as school_id_views
url(r'^nidreturn$', school_id_view.return_nid, name='nretrun_nid'),
url(r'^unlink_account$', school_id_views.unidlink, name='unidlink_account'),
```
網址是一樣的，但是意義差很多

2019-05-03 02:58 UTC, guangyaw commented
已移動code , 請查收

2019-05-14 02:12 UTC, guangyaw commented
請問nid目前進度

2019-05-17 04:24 UTC, yrchen requested changes
我還是沒有看到 migrations 檔案，請補上

2019-05-17 05:47 UTC, guangyaw commented
原有migrations有太多非必要東西,
請於lms/djangoapps/ 新建一個同名app再將檔案弄進去即可

2019-05-17 07:05 UTC, yrchen commented
> 原有migrations有太多非必要東西,
> 請於lms/djangoapps/ 新建一個同名app再將檔案弄進去即可

現在這個 PR 的 migrations 資料夾裡面只有一個 __init__.py
哪來太多非必要的東西？

請 makemigrations 以後，把 school_nid_login/migrations 資料夾的檔案放進來，這樣我才有 migrations 檔案可以使用

2019-05-17 09:20 UTC, guangyaw commented
好了  請查收

2019-05-29 10:11 UTC, guangyaw commented
move the client id setting into Django admin

2019-06-11 03:27 UTC, yrchen approved these changes

2019-06-11 03:27 UTC, merged