Hawthorn 教育雲端帳號登入 for openedu
OpenEduTW/edx-platform pull request #9
Opened 2020-01-15 08:01 UTC by guangyaw

2.add lost file for cloud.edu login
3.add icons for cloud.edu login
4.remove useless code and correct the message
5.change the name of the cloud.edu login

2020-01-15 08:16 UTC, yrchen requested changes

2020-01-15 08:16 UTC, yrchen commented on lms/djangoapps/school_id_login/views.py
> +    redirect_url = "https://www.openedu.tw"
可以的話盡量避免把網址寫在 codes 裡面吧，這邊有環境變數可以用

2020-01-15 08:16 UTC, yrchen commented on lms/djangoapps/school_id_login/views.py
> +                            'error_msg1': "成功登入教育雲端帳號,但此帳號未與中華開放教育平台帳號綁定",
中文訊息中的標點符號，請統一使用全形

2020-01-15 08:16 UTC, yrchen commented on lms/envs/aws.py
>  ##### guangyaw add school id login #####
如果下一行刪除了，那這行註解完全是多的

2020-01-15 08:16 UTC, yrchen commented on lms/static/js/student_account/views/account_settings_factory.js
> +                                    connectUrl: "https://courses.openedu.tw/oidlogin",
一樣，網址請不要定義在 code 裡面，不然你無法在 stage/sandbox 環境測試

2020-01-16 03:21 UTC, guangyaw commented
fix the request.

2020-01-20 09:38 UTC, yrchen approved these changes
LGTM

2020-01-20 09:38 UTC, merged